export const GLOBAL_MISSING_REQUIRED_PARAMETER_ERROR_CODE = 'ERR_1000'
export const GLOBAL_WRONG_MAIL_FORMAT_ERROR_CODE = 'ERR_1001'
export const GLOBAL_NOT_ALLOWED_CHARACTER_ERROR_CODE = 'ERR_1002'

export const USER_NOT_ALLOWED_ERROR_CODE = 'ERR_2000'
export const USER_INVALID_CREDENTIALS_ERROR_CODE = 'ERR_2001'
export const USER_MAIL_ALREADY_USED_ERROR_CODE = 'ERR_2002'